version: "3"

services:
  sonarqube:
    image: sonarqube:10.1.0-community
    depends_on:
      - sonar_db
    env_file: 
      - .env.sq
    ports:
      - "9001:9000"
    volumes:
      - ./sonarqube_conf:/opt/sonarqube/conf
      - ./sonarqube_data:/opt/sonarqube/data
      - ./sonarqube_extensions:/opt/sonarqube/extensions
      - ./sonarqube_logs:/opt/sonarqube/logs
      - ./sonarqube_temp:/opt/sonarqube/temp

  sonar_db:
    image: postgres:15.4-alpine
    env_file: 
      - .env.db
    volumes:
      - ./sonar_db:/var/lib/postgresql
      - ./sonar_db_data:/var/lib/postgresql/data

        #volumes:
        #  sonarqube_conf:
        #  sonarqube_data:
        #  sonarqube_extensions:
#  sonarqube_logs:
#  sonarqube_temp:
#  sonar_db:
#  sonar_db_data:
