AWSTemplateFormatVersion: "2010-09-09"
Resources:
  MyKey:
    Type: AWS::EC2::KeyPair
    Properties:
      Tags:
        - Key: Name
          Value: mykey
  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
  Ec2Instance:
    Type: AWS::EC2::Intance
    Properties:
      ImageId:
      InstanceType: t2.micro
      SecurityGroupId: !Ref SecurityGroup
      KeyName: !Ref MyKey
      Tags:
        - Key: Name
          Value: test-instance
