version: "3"
services:
  gitlab:
    image: gitlab/gitlab-ce:15.11.2-ce.0
    hostname: kaif
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - '2222:2222'
      - '80:80'
      - '443:443'
      - '5050:5050'
    volumes:
      - /mnt/1tb/gitlab/gitlab_config:/etc/gitlab
      - /mnt/1tb/gitlab/gitlab_logs:/var/log/gitlab
      - /mnt/1tb/gitlab/gitlab_data:/var/opt/gitlab

  gitlab-runner:
    image: gitlab/gitlab-runner:alpine3.15-v15.11.0
    restart: unless-stopped
    volumes:
      - /mnt/1tb/gitlab/gitlab_runner/config/:/etc/gitlab-runner/
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  gitlab_config:
  gitlab_logs:
  gitlab_data:



    #RAILS_ENV=
    #GITLAB_HOST=
    #GITLAB_OMNIBUS_CONFIG=external_url ''    
